#secrets:
#  - name: API_KEY
#    value: '${{ secrets.API_KEY }}'

image:
  repository: docker.pkg.github.com/bard86/githubactions/githubactionsdemo
  pullPolicy: Always
  tag: latest

imagePullSecrets:
  - name: github-pkg
