---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deliverybot-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: deliverybot
    namespace: example-helm
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
