name: Java CD to K8S
on:
  deployment

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v1'

#      - name: 'Deploy'
#        uses: 'deliverybot/helm@master'
#        with:
#          token: '${{ github.token }}'
#          secrets: '${{ toJSON(secrets) }}'
#          version: '${{ github.sha }}'
#          chart: 'app'
#          helm: helm3
#        env:
#          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      - name: 'Deploy'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: whoami